# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'ordering': ['-id'],
                'verbose_name': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio')),
                ('type_of_purchase', models.CharField(choices=[('Diario', 'Diario'), ('Semanal', 'Semanal'), ('Quincenal', 'Quincenal'), ('Mensual', 'Mensual'), ('Bimensual', 'Bimensual'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], max_length=30, verbose_name='Tipo de compra')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.Category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name_plural': 'Producto',
                'ordering': ['-id'],
                'verbose_name': 'Producto',
            },
        ),
    ]
